name: flutter_simple_usestate
description: "A simple and lightweight state management library."
version: 0.0.1
homepage: https://github.com/nimahedayati/flutter_simple_usestate

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
